# WebAPI 描述文件

# 打开在线编辑器 https://editor.swagger.io/
# 把全文复制到左侧编辑器中

# Author: 王润基
# Created: 2017.10.15

swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "MediaManager"
  termsOfService: "http://47.94.142.165:8088/gitlab/PRJ1_PraiseTheSun/MediaManager"
  contact:
    email: "wangrunji0408@163.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8000"
basePath: "/"
tags:
- name: "user"
  description: "Operations about user"
- name: "group"
  description: "Operations about usergroup"
- name: "file"
  description: "Operations about file"
schemes:
- "http"
paths:
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "管理员用户创建新用户"
      operationId: "createUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
    get:
      tags:
      - "user"
      summary: "Get user by query"
      description: "搜索用户"
      operationId: "getUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "User name regex"
        type: "string"
      - name: "group"
        in: "query"
        description: "User group id"
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
  /user/signup:
    post:
      tags:
      - "user"
      summary: "Signup user"
      description: "游客自助注册用户"
      operationId: "signupUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "只有部分值是有用的 username password email phone"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /user/{username}:
    get:
      tags:
      - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserByName"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be fetched. Use user1 for testing. "
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
    put:
      tags:
      - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the admin user."
      operationId: "deleteUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /group:
    post:
      tags:
      - "group"
      summary: "Create group"
      description: "管理员用户创建新用户组"
      operationId: "createUserGroup"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user group"
        required: true
        schema:
          $ref: "#/definitions/UserGroup"
      responses:
        default:
          description: "successful operation"
    get:
      tags:
      - "group"
      summary: "Get all user groups"
      description: ""
      operationId: "getUserGroups"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserGroup"
  /group/{id}:
    get:
      tags:
      - "group"
      summary: "Get group by id"
      description: ""
      operationId: "getUserGroupById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserGroup"
        404:
          description: "User group not found"
    put:
      tags:
      - "group"
      summary: "Updated group"
      operationId: "updateUserGroup"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Updated group object"
        required: true
        schema:
          $ref: "#/definitions/UserGroup"
      responses:
        200:
          description: "successful operation"
        404:
          description: "User group not found"
    delete:
      tags:
      - "group"
      summary: "Delete user group"
      description: "删除用户组，同时删除组内用户的标记"
      operationId: "deleteUserGroup"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
        404:
          description: "User group not found"
  /file:
    post:
      tags:
      - "file"
      summary: "Create file or directory"
      description: "新建空白文件或文件夹"
      operationId: "createFile"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created file object"
        required: true
        schema:
          $ref: "#/definitions/File"
      responses:
        default:
          description: "successful operation"
    get:
      tags:
      - "file"
      summary: "Get file infos by query"
      description: "Used for searching files"
      operationId: "getFiles"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "path"
        in: "query"
        description: "File path"
        type: "string"
      - name: "name"
        in: "query"
        description: "File name"
        type: "string"
      - name: "tags"
        in: "query"
        description: "File tags"
        type: "array"
        items:
          type: "string"
      - name: "orderby"
        in: "query"
        description: "Orderby"
        type: "string"
        enum:
        - "name"
        - "modifyDate"
      - name: "order"
        in: "query"
        description: "ascending / descending"
        type: "string"
        enum:
        - "ascending"
        - "descending"
        default: "ascending"
      - name: "page"
        in: "query"
        description: "Page number. Begin from 1."
        type: "integer"
      - name: "pagesize"
        in: "query"
        description: "Page size. Default = 10."
        type: "integer"
        default: 10
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/File"
        404:
          description: "File not found or is invisible for user"
  /file/{id}:
    get:
      tags:
      - "file"
      summary: "Get file info by Id"
      description: "Used for searching files"
      operationId: "getFileById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        description: "File id"
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/File"
        404:
          description: "File not found or is invisible for user"
    delete:
      tags:
      - "file"
      summary: "Delete file or directory"
      description: ""
      operationId: "deleteFile"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        description: "File id"
        type: "string"
      responses:
        200:
          description: "successful operation"
        404:
          description: "File not found"
  /file/upload:
    post:
      tags:
      - "file"
      summary: "Upload file"
      description: "上传文件"
      operationId: "uploadFile"
      produces:
      - "application/xml"
      - "application/json"
      consumes:
      - "multipart/form-data"
      parameters:
      - in: formData
        name: file
        type: file
        description: The file to upload.
      responses:
        default:
          description: "successful operation"

definitions:
  File:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      directory:
        type: "boolean"
      name:
        type: "string"
        description: "文件名"
      path:
        type: "string"
        description: "文件绝对路径，不含文件名"
      url:
        type: "string"
        description: "Download link"
      md5:
        type: "string"
      thumbnails:
        type: "string"
        description: "image url"
      size:
        type: "integer"
        format: "int32"
        description: "in bytes"
      modifyDate:
        type: "string"
        format: "date-time"
      createDate:
        type: "string"
        format: "date-time"
      tags:
        type: "array"
        items:
          $ref: "#/definitions/FileTag"
    xml:
      name: "File"
  UserGroup:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "UserGroup"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      password:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      image:
        type: "string"
        description: "头像图片地址"
      groups:
        type: "array"
        items:
          $ref: "#/definitions/UserGroup"
    xml:
      name: "User"
  FileTag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      color:
        type: "string"
    xml:
      name: "FileTag"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"